train:
  multiwoz:
    path: data/from_lumi/prep_dial_multiwoz_train # path to dataset, if empty will use HF_DATASET_PATH
    split: train
  spokenwoz:
    path: data/from_lumi/prep_dial_spokenwoz_allColumns_train
    split: train

validation:
  multiwoz:
    path: data/from_lumi/prep_dial_multiwoz_train
    split: validation
  spokenwoz:
    path: data/from_lumi/prep_dial_spokenwoz_allColumns_train
    split: validation

text_train:
  multiwoz:
    path: data/from_lumi/prep_dial_multiwoz_train
    split: train
